package org.niord.s125.utils;

import _int.iala_aism.s125.gml._0_0.*;
import _int.iala_aism.s125.gml._0_0.ObjectFactory;
import _int.iho.s100.gml.base._1_0.*;
import _int.iho.s100.gml.base._1_0.CurveType;
import _int.iho.s100.gml.base._1_0.PointType;
import _net.opengis.gml.profiles.*;
import org.locationtech.jts.geom.Point;
import org.niord.core.aton.AtonNode;
import org.niord.core.aton.AtonTag;
import org.niord.core.geojson.GeoJsonUtils;
import org.niord.core.geojson.JtsConverter;
import org.niord.model.geojson.CrsVo;
import org.niord.model.geojson.GeoJsonVo;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.JAXBException;
import javax.xml.namespace.QName;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;

import static org.niord.core.aton.AtonTag.TAG_ATON_TYPE;

public class S125Utils {

    /**
     * Packages the provided list of AtoN nodess into an S125 dataset as
     * dictated by the NIPWG S-125 data product specification.
     *
     * @param atonNodes      The list of S-125 AtoN nodes
     */
    public static DataSet packageToDataset(String dataSetId,
                                           List<AtonNode> atonNodes,
                                           String agency,
                                           String language) {
        // Initialise the dataset
        DataSet s125Dataset = new DataSet();
        s125Dataset.setId(dataSetId);

        //====================================================================//
        //                       BOUNDED BY SECTION                           //
        //====================================================================//
        // Calculate the bounding by envelope
        List<GeoJsonVo> geoJsonAList = atonNodes.stream()
                .map(AtonNode::getGeometry)
                .map(JtsConverter::fromJts)
                .collect(Collectors.toList());
        String srsName = geoJsonAList.stream()
                .findFirst()
                .map(GeoJsonVo::getCrs)
                .map(CrsVo::getType)
                .orElse("EPSG:4326");
        double bbox[] = GeoJsonUtils.computeBBox(geoJsonAList.toArray(GeoJsonVo[]::new));
        Pos lowerCorner = new Pos();
        lowerCorner.getValues().add(bbox[1]);
        lowerCorner.getValues().add(bbox[0]);
        Pos upperCorner = new Pos();
        upperCorner.getValues().add(bbox[3]);
        upperCorner.getValues().add(bbox[2]);

        // And create the bounding by envelop
        BoundingShapeType boundingShapeType = new BoundingShapeType();
        EnvelopeType envelopeType = new EnvelopeType();
        envelopeType.setSrsName(srsName);
        envelopeType.setLowerCorner(lowerCorner);
        envelopeType.setUpperCorner(upperCorner);
        boundingShapeType.setEnvelope(envelopeType);
        s125Dataset.setBoundedBy(boundingShapeType);

        //====================================================================//
        //                  DATASET IDENTIFICATION SECTION                    //
        //====================================================================//
        DataSetIdentificationType dataSetIdentificationType = new DataSetIdentificationType();
        dataSetIdentificationType.setEncodingSpecification("S100 Part 10b");
        dataSetIdentificationType.setEncodingSpecificationEdition("1.0");
        dataSetIdentificationType.setProductIdentifier("S-125");
        dataSetIdentificationType.setProductEdition("0.0.1");
        dataSetIdentificationType.setDatasetFileIdentifier("S-125_GRAD_"+ dataSetId);
        dataSetIdentificationType.setDatasetTitle("Niord S-125 Dataset");
        dataSetIdentificationType.setDatasetReferenceDate(new Date());
        dataSetIdentificationType.setDatasetLanguage(ISO6391.EN);
        dataSetIdentificationType.setDatasetAbstract("Autogenerated S-125 Dataset for" + atonNodes.stream()
                .map(AtonNode::getAtonUid)
                .map(uid -> String.format(" %s", uid))
                .collect(Collectors.joining()));
        s125Dataset.setDatasetIdentificationInformation(dataSetIdentificationType);

        //====================================================================//
        //              DATASET STRUCTURE INFORMATION SECTION                 //
        //====================================================================//
        DataSetStructureInformationType dataSetStructureInformationType = new DataSetStructureInformationType();
        dataSetStructureInformationType.setCoordMultFactorX(BigInteger.ONE);
        dataSetStructureInformationType.setCoordMultFactorY(BigInteger.ONE);
        dataSetStructureInformationType.setCoordMultFactorZ(BigInteger.ONE);

        //====================================================================//
        //                      DATASET MEMBERS SECTION                       //
        //====================================================================//
        AtomicInteger idIndex = new AtomicInteger(1);
        Optional.ofNullable(atonNodes)
                .orElse(Collections.emptyList())
                .stream()
                .map(aton -> S125Utils.generateAidsToNavigation(idIndex, aton))
                .map(jaxb -> { MemberType m = new MemberType(); m.setAbstractFeature(jaxb); return m; })
                .forEach(s125Dataset.getImembersAndMembers()::add);
        // Return the dataset
        return s125Dataset;
    }

    /**
     * This is the entry method static function of the utility. It will examine
     * the provided AtoN Node from Niord and generate a standardised S-125
     * format messages based on the specifications specified by the IHO/IALA
     * NIPWG.
     *
     * @param atonNode      The Niord AtoN node object
     * @return The generated S-125 data message
     */
    public static JAXBElement<? extends S125AidsToNavigationType> generateAidsToNavigation(AtomicInteger idIndex, AtonNode atonNode) {
        // First read the AtoN type information from the input
        String atonType = atonNode.getTagValue(TAG_ATON_TYPE);
        // Now initialise the JAXB object factory to generate the member
        ObjectFactory factory = new ObjectFactory();
        JAXBElement<? extends S125AidsToNavigationType> jaxbElement =  null;
        // Handle each possible type, cause a different object should be created
        switch(atonType) {
            case "beacon_cardinal":
                jaxbElement = factory.createS125BeaconCardinal(generateBeaconCardinal(idIndex, atonNode));
                break;
            case "beacon_lateral":
                jaxbElement = factory.createS125BeaconLateral(generateBeaconLateral(idIndex, atonNode));
                break;
            case "beacon_isolated_danger":
                jaxbElement = factory.createS125BeaconIsolatedDanger(generateBeaconIsolatedDanger(idIndex, atonNode));
                break;
            case "beacon_safe_water":
                jaxbElement = factory.createS125BeaconSafeWater(generateBeaconSafeWater(idIndex, atonNode));
                break;
            case "beacon_special_purpose":
                jaxbElement = factory.createS125BeaconSpecialPurposeGeneral(generateBeaconSpecialPurpose(idIndex, atonNode));
                break;
            case "buoy_cardinal":
                jaxbElement = factory.createS125BuoyCardinal(generateBuoyCardinal(idIndex, atonNode));
                break;
            case "buoy_lateral":
                jaxbElement = factory.createS125BuoyLateral(generateBuoyLateral(idIndex, atonNode));
                break;
            case "buoy_installation":
                jaxbElement = factory.createS125BuoyInstallation(generateBuoyInstallation(idIndex, atonNode));
                break;
            case "buoy_isolated_danger":
                jaxbElement = factory.createS125BuoyIsolatedDanger(generateBuoyIsolatedDanger(idIndex, atonNode));
                break;
            case "buoy_safe_water":
                jaxbElement = factory.createS125BuoySafeWater(generateBuoySafeWater(idIndex, atonNode));
                break;
            case "buoy_special_purpose":
                jaxbElement = factory.createS125BuoySpecialPurposeGeneral(generateBuoySpecialPurpose(idIndex, atonNode));
                break;
            case "light":
                jaxbElement = factory.createS125Light(generateLight(idIndex, atonNode));
                break;
            case "light_vessel":
                jaxbElement = factory.createS125LightVessel(generateLightVessel(idIndex, atonNode));
                break;
            case "virtual_aton":
                jaxbElement = factory.createS125VirtualAISAidToNavigation(generateVirtualAtoN(idIndex, atonNode));
                break;
        }
        // And return what was generated
        return jaxbElement;
    }

    /**
     * Generate the S-125 dataset member section for Beacon Cardinal AtoNs.
     *
     * @param atonNode      The AtoN node to be used for the member
     * @return The S-125 dataset member section generated
     */
    private static S125BeaconCardinalType generateBeaconCardinal(AtomicInteger idIndex, AtonNode atonNode) {
        S125BeaconCardinalType member = new S125BeaconCardinalType();
        return member;
    }

    /**
     * Generate the S-125 dataset member section for Beacon Lateral AtoNs.
     *
     * @param atonNode      The AtoN node to be used for the member
     * @return The S-125 dataset member section generated
     */
    private static S125BeaconLateralType generateBeaconLateral(AtomicInteger idIndex, AtonNode atonNode) {
        S125BeaconLateralType member = new S125BeaconLateralType();
        return  member;
    }

    /**
     * Generate the S-125 dataset member section for Beacon Isolated Danger
     * AtoNs.
     *
     * @param atonNode      The AtoN node to be used for the member
     * @return The S-125 dataset member section generated
     */
    private static S125BeaconIsolatedDangerType generateBeaconIsolatedDanger(AtomicInteger idIndex, AtonNode atonNode) {
        S125BeaconIsolatedDangerType member = new S125BeaconIsolatedDangerType();
        return member;
    }

    /**
     * Generate the S-125 dataset member section for Beacon Safe Water AtoNs.
     *
     * @param atonNode      The AtoN node to be used for the member
     * @return The S-125 dataset member section generated
     */
    private static S125BeaconSafeWaterType generateBeaconSafeWater(AtomicInteger idIndex, AtonNode atonNode) {
        S125BeaconSafeWaterType member = new S125BeaconSafeWaterType();
        return member;
    }

    /**
     * Generate the S-125 dataset member section for Beacon Special Purpose
     * AtoNs.
     *
     * @param atonNode      The AtoN node to be used for the member
     * @return The S-125 dataset member section generated
     */
    private static S125BeaconSpecialPurposeGeneralType generateBeaconSpecialPurpose(AtomicInteger idIndex, AtonNode atonNode) {
        S125BeaconSpecialPurposeGeneralType member = new S125BeaconSpecialPurposeGeneralType();
        return member;
    }

    /**
     * Generate the S-125 dataset member section for Buoy Cardinal AtoNs.
     *
     * @param atonNode      The AtoN node to be used for the member
     * @return The S-125 dataset member section generated
     */
    private static S125BuoyCardinalType generateBuoyCardinal(AtomicInteger idIndex, AtonNode atonNode) {
        S125BuoyCardinalType member = new S125BuoyCardinalType();
        return member;
    }

    /**
     * Generate the S-125 dataset member section for Buoy Lateral AtoNs.
     *
     * @param atonNode      The AtoN node to be used for the member
     * @return The S-125 dataset member section generated
     */
    private static S125BuoyLateralType generateBuoyLateral(AtomicInteger idIndex, AtonNode atonNode) {
        S125BuoyLateralType member = new S125BuoyLateralType();
        return member;
    }

    /**
     * Generate the S-125 dataset member section for Buoy Installation AtoNs.
     *
     * @param atonNode      The AtoN node to be used for the member
     * @return The S-125 dataset member section generated
     */
    private static S125BuoyInstallationType generateBuoyInstallation(AtomicInteger idIndex, AtonNode atonNode) {
        S125BuoyInstallationType member = new S125BuoyInstallationType();
        return member;
    }

    /**
     * Generate the S-125 dataset member section for Buoy Isolated Dander AtoNs.
     *
     * @param atonNode      The AtoN node to be used for the member
     * @return The S-125 dataset member section generated
     */
    private static S125BuoyIsolatedDangerType generateBuoyIsolatedDanger(AtomicInteger idIndex, AtonNode atonNode) {
        S125BuoyIsolatedDangerType member = new S125BuoyIsolatedDangerType();
        return member;
    }

    /**
     * Generate the S-125 dataset member section for Buoy Safe Water AtoNs.
     *
     * @param atonNode      The AtoN node to be used for the member
     * @return The S-125 dataset member section generated
     */
    private static S125BuoySafeWaterType generateBuoySafeWater(AtomicInteger idIndex, AtonNode atonNode) {
        S125BuoySafeWaterType member = new S125BuoySafeWaterType();
        return member;
    }

    /**
     * Generate the S-125 dataset member section for Buoy Special Purpose AtoNs.
     *
     * @param atonNode      The AtoN node to be used for the member
     * @return The S-125 dataset member section generated
     */
    private static S125BuoySpecialPurposeGeneralType generateBuoySpecialPurpose(AtomicInteger idIndex, AtonNode atonNode) {
        S125BuoySpecialPurposeGeneralType member = new S125BuoySpecialPurposeGeneralType();
        return member;
    }

    /**
     * Generate the S-125 dataset member section for Light AtoNs.
     *
     * @param atonNode      The AtoN node to be used for the member
     * @return The S-125 dataset member section generated
     */
    private static S125LightType generateLight(AtomicInteger idIndex, AtonNode atonNode) {
        S125LightType member = new S125LightType();
        return member;
    }

    /**
     * Generate the S-125 dataset member section for Light Vessel AtoNs.
     *
     * @param atonNode      The AtoN node to be used for the member
     * @return The S-125 dataset member section generated
     */
    private static S125LightVesselType generateLightVessel(AtomicInteger idIndex, AtonNode atonNode) {
        S125LightVesselType member = new S125LightVesselType();
        return member;
    }

    /**
     * Generate the S-125 dataset member section for Virtual AtoNs.
     *
     * @param atonNode      The AtoN node to be used for the member
     * @return The S-125 dataset member section generated
     */
    private static S125VirtualAISAidToNavigationType generateVirtualAtoN(AtomicInteger idIndex, AtonNode atonNode) {
        S125VirtualAISAidToNavigationType member = new S125VirtualAISAidToNavigationType();
        member.setId(String.format("ID%03d", idIndex.getAndIncrement()));
        member.setIdCode(Integer.toString(atonNode.getId()));
        FeatureObjectIdentifier featureObjectIdentifier = new FeatureObjectIdentifier();
        featureObjectIdentifier.setAgency("GRAD");
        member.setAtonNumber(Optional.of("mrn")
                .map(atonNode::getTag)
                .map(AtonTag::getV)
                .orElse(null));
        member.setMMSICode(Optional.of("seamark:virtual_aton:mmsi")
                .map(atonNode::getTag)
                .map(AtonTag::getV)
                .map(BigDecimal::new)
                .orElse(null));
        member.setObjectName(Optional.of("seamark:name")
                .map(atonNode::getTag)
                .map(AtonTag::getV)
                .orElse(null));
        member.setObjectNameInNationalLanguage(Optional.of("seamark:name")
                .map(atonNode::getTag)
                .map(AtonTag::getV)
                .orElse(null));
        member.setStatus(Optional.of("seamark:status")
                .map(atonNode::getTag)
                .map(AtonTag::getV)
                .map(v -> {try {return S125Status.fromValue(v);} catch (Exception ex) {return null;}})
                .orElse(S125Status.EXISTENCE_DOUBTFUL));
        member.setVirtualAISAidToNavigationType(Optional.of("seamark:virtual_aton:category")
                .map(atonNode::getTag)
                .map(AtonTag::getV)
                .map(v -> v.replace(" ", "_"))
                .map(v -> {try {return S125VirtualAISAidToNavigationPurposeType.fromValue(v);} catch (Exception ex) {return null;}})
                .orElse(S125VirtualAISAidToNavigationPurposeType.SPECIAL_PURPOSE));

        // Now fix the geometry... from a point to a curve???
        _int.iho.s100.gml.base._1_0_Ext.CurveProperty curvePropertyExt = new _int.iho.s100.gml.base._1_0_Ext.CurveProperty();
        CurveProperty curveProperty = new CurveProperty();
        CurveType curveType = new CurveType();
        Segments segments = new Segments();
        LineStringSegmentType lineStringSegmentType = new LineStringSegmentType();
        PosList posList = new PosList();
        posList.getValues().add(atonNode.getLat());
        posList.getValues().add(atonNode.getLon());
        lineStringSegmentType.setPosList(posList);
        JAXBElement<LineStringSegmentType> element = new _net.opengis.gml.profiles.ObjectFactory().createLineStringSegment(lineStringSegmentType);
        segments.getAbstractCurveSegments().add(element);
        curveType.setId(String.format("ID%03d", idIndex.getAndIncrement()));
        curveType.setSegments(segments);
        curveProperty.setCurve(curveType);
        curvePropertyExt.setCurveProperty(curveProperty);
        member.setGeometry(curvePropertyExt);

        // And return the populated member
        return member;
    }

    /**
     * Populates and return an S-125 point property based on a point geometry
     *
     * @param point     The point geometry
     * @return The populated point property
     */
    public static PointProperty generatePointProperty(Point point) {
        // Generate the elements
        PointProperty pointProperty = new PointProperty();
        PointType pointType = new PointType();
        Pos pos = new Pos();

        // Populate with the geometry data
        pos.setSrsName("EPSG:4326");
        pos.getValues().add(point.getY());
        pos.getValues().add(point.getX());

        // Populate the elements
        pointType.setPos(pos);
        pointProperty.setPoint(pointType);

        // And return the output
        return pointProperty;
    }

}
